KILOGRAMS = 'kilograms'
GRAMS = 'grams'
POUNDS = 'pounds'
OUNCES = 'ounces'
WEIGHT_UNITS = [KILOGRAMS, GRAMS, POUNDS, OUNCES]

INCHES = 'inches'
CENTIMETERS = 'centimeters'
FEET = 'feet'
METERS = 'meters'
LENGTH_UNITS = [INCHES, CENTIMETERS, FEET, METERS]

HALF_DAY = 12 * 60 * 60
ONE_DAY = 24 * 60 * 60
ONE_WEEK = ONE_DAY * 7
